updates action

diff --git a/.github/workflows/gen.yml b/.github/workflows/gen.yml
--- a/.github/workflows/gen.yml
+++ b/.github/workflows/gen.yml
@@ -1,4 +1,4 @@
-name: gen
+name: Generation
 
 on:
   pull_request:
@@ -12,21 +12,34 @@ env:
   RUSTFLAGS: -Dwarnings
 
 jobs:
-  generation:
-    name: tool_${{ matrix.tool }}
-    runs-on: ubuntu-latest
+  rust:
     strategy:
       matrix:
         tool: [windows_app, targets]
+    name: '`tool_${{ matrix.tool }}`'
+    runs-on: windows-2022
     steps:
       - name: Checkout
         uses: actions/checkout@v3
-      - name: Update toolchain
+      - name: Update rust toolchain
         run: rustup update --no-self-update stable && rustup default stable
-      - name: Run
+      - name: Run generation
         run: cargo run -p tool_${{ matrix.tool }}
       - name: Check
-        shell: bash
         run: |
           git add -N .
           git diff --exit-code || (echo '::error::Generated `tool_${{ matrix.tool }}` is out-of-date. Please run `cargo run -p tool_${{ matrix.tool }}`'; exit 1)
+
+  metadata:
+    name: Metadata, `.lib`s and `.dll`s
+    runs-on: windows-2022
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v3
+      - name: Generate
+        working-directory: ./metadata
+        run: dotnet build
+      - name: Check
+        run: |
+          git add -N .
+          git diff --exit-code || (echo '::error::Generated Windows metadata is out-of-date. Please run `dotnet build` in `./metadata`'; exit 1)
